package main

import "fmt"

/*
  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
  By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million,
  find the sum of the even-valued terms.

  Answer = 4613732
*/

func solution() int {
	const LIMIT = 4_000_000
	var sum, cur, next, temp = 2, 1, 2, 0
	isExceed := false
	for !isExceed {
		temp = cur
		cur = next
		next += temp
		isExceed = next > LIMIT
		if (next&0x1) == 0 && !isExceed {
			sum += next
		}
	}
	return sum
}

func main() {
	fmt.Println("Solution: ", solution())
}
